- hosts: localhost
  gather_facts: False
  tasks:
  - set_fact:
      current:
        config:
          - afi: ipv4
            acls:
              - name: 110
                aces:
                  - grant: deny
                    sequence: 10
                    protocol_options:
                      icmp:
                        traceroute: true
                    source:
                      address: 192.0.2.0
                      wildcard_bits: 0.0.0.255
                    destination:
                      address: 192.0.3.0
                      wildcard_bits: 0.0.0.255
                    dscp: ef
                    ttl:
                      eq: 10
      modified:
        config:
          - afi: ipv4
            acls:
              - name: 110
                aces:
                  - grant: deny
                    sequence: 10
                    protocol_options:
                      icmp:
                        traceroute: true
                    source:
                      address: 192.0.2.0
                      wildcard_bits: 0.0.0.255
                    destination:
                      address: 192.0.3.0
                      wildcard_bits: 0.0.0.255
                    dscp: af31
                    ttl:
                      eq: 10
  

  - cidrblock.devpak.fact_diff:
      before: "{{ current|cidrblock.devpak.to_dotted }}"
      after: "{{ modified|cidrblock.devpak.to_dotted }}"
